logging:
  level:
    root: WARN
    org:
      springframework:
        web: ERROR
      hibernate: DEBUG
    com:
      ill:
        transactional: DEBUG
        controller: DEBUG
  file: song.log
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
debug: true